#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config window_gap          15

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#e0b0ff"
bspc config presel_feedback_color "#6272a4"

#bspc config active_border_color "#6272a4"
#bspc config focused_border_color "#8be9fd"



bspc config split_ratio          0.5

bspc config focus_follows_pointer true
bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

